apiVersion: v1
kind: Service
metadata:
  name: ros2-talker-domain2
  labels:
    app: ros2-talker-domain2
spec:
  selector:
    app: ros2-talker-domain2
  ports:
  - port: 7400
    targetPort: 7400
    name: dds
  clusterIP: None
