apiVersion: v1
kind: Service
metadata:
  name: fastdds-discovery-server-domain2
  labels:
    app: fastdds-discovery-server-domain2
spec:
  selector:
    app: fastdds-discovery-server-domain2
  ports:
  - port: 11811
    targetPort: 11811
    name: discovery
  clusterIP: None
