apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - base/fastdds-discovery-server/
  - base/ros2-talker/
  - base/ros2-listener/
  - base/ros2-listener-distributed/
